### ISSUE TITLE
Zheng dataset

### ISSUE THREAD

**Issue by dustinlong** [taolonglab/himap#3]
Is the Zheng dataset used in the HiMAP publication and the mock community GitHub tutorial ("~/data/zheng_2015_tutorial") available for download? I have not been able to locate a data source in the original publication or in SRA.

Many thanks,

Dustin Long

**Comment by igor25** [comment]
Hi Dustin,

I got the files from the authors of the paper by directly e-mailing them. I can send you the FASTQ files privately, since it's not really my data.

I'll e-mail the authors again and ask for the permission to just upload them myself on the NCBI SRA. No idea why they didn't upload them anywhere in the first place (especially since the article itself is Open Access...).

**Comment by dustinlong** [comment]
Fantastic!

If you wouldn't mind sharing the FASTQs, that would be great. I can set up a file transfer server or  private dropbox file request if that would be convenient. Let me know what's best for you.

Thanks again,

Dustin
drlong@uw.edu
